### ISSUE TITLE
Keep up the great work going 🙏

### ISSUE THREAD

**Issue by mhdsnj** [Divested-Mobile/Mull#3]
Firstly would like to thank everyone behind the project... THANK YOU. I'm not able to visit the apple official website. What's happening?.

**Comment by SkewedZeppelin** [comment]
Go to about:config and change security.OCSP.require to false.

**Comment by mhdsnj** [comment]
> Go to about:config and change security.OCSP.require to false.
> 

That did it!. Thank You. You're a gem!
